import "@/styles/animation.css";
import "@/styles/globals.css";
import { cabinet_grotesk } from "@/utils/Font";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dogoshi",
  description: "Generated by Dogoshi",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cabinet_grotesk.className}>
        <main> {children}</main>
      </body>
    </html>
  );
}
